go:
    version: 1.25.0
    cgo: false
repository:
    path: github.com/ubccr/eaton_exporter
build:
    prefix: .
    binaries:
        - name: eaton_exporter
          path: .
    flags: -a -tags netgo
    ldflags: |
        -s
        -X {{repoPath}}/version.Version={{.Version}}
        -X {{repoPath}}/version.Revision={{.Revision}}
        -X {{repoPath}}/version.Branch={{.Branch}}
        -X {{repoPath}}/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    prefix: .
    files:
        - CHANGELOG.md
        - README.md
        - LICENSE
crossbuild:
    platforms:
        - linux/amd64
